# Generated by Django 4.2.9 on 2024-01-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('sala', models.CharField(max_length=10)),
                ('curso', models.CharField(max_length=50)),
                ('turma', models.CharField(max_length=10)),
                ('professor', models.CharField(max_length=50)),
                ('disciplina', models.CharField(max_length=50)),
            ],
        ),
    ]
