# Generated by Django 5.0.1 on 2024-02-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProfessor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicial', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('sala', models.CharField(max_length=80)),
                ('curso', models.CharField(max_length=80)),
                ('turma', models.CharField(max_length=80)),
                ('professor', models.CharField(max_length=80)),
                ('disciplina', models.CharField(max_length=80)),
                ('data', models.CharField(blank=True, max_length=10, null=True)),
                ('turno', models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno')], max_length=15, null=True)),
            ],
        ),
    ]
