# Generated by Django 5.0.1 on 2024-02-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenca_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroprofessor',
            options={'verbose_name_plural': 'Registro de Sala'},
        ),
    ]
