# Generated by Django 4.2.9 on 2024-01-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroprofessor',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroprofessor',
            name='hora_inicial',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
