# Generated by Django 4.2.9 on 2024-01-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca_app', '0002_alter_registroprofessor_hora_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroprofessor',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
