# Generated by Django 4.2.9 on 2024-01-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca_app', '0004_alter_registroprofessor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroprofessor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
