# Generated by Django 5.0.1 on 2024-01-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca_app', '0005_alter_registroprofessor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroprofessor',
            name='curso',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='registroprofessor',
            name='disciplina',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='registroprofessor',
            name='professor',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='registroprofessor',
            name='sala',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='registroprofessor',
            name='turma',
            field=models.CharField(max_length=80),
        ),
    ]
