# Generated by Django 5.0.1 on 2024-01-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca_app', '0006_alter_registroprofessor_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroprofessor',
            name='turno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
